# Generated by Django 3.1.3 on 2020-11-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201104_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Hostname',
        ),
    ]
